server {
    listen 80;
    
    # Katalog główny z plikami frontendu
    root /app/dist;
    index index.html;

    # Obsługa routingu dla aplikacji jednostronicowej (SPA) jak Vue
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Przekierowanie zapytań do API do serwera FastAPI
    # Wszystkie zapytania zaczynające się od /upload/ zostaną przekazane
    location /upload/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}